import logging
import os
from pathlib import Path

import hydra
import numpy as np
import polars as pl
from datasets import concatenate_datasets, load_dataset
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams

from configs.evaluate_config import Config

logging.basicConfig(format="%(asctime)s - %(levelname)s - %(message)s", level=logging.WARNING)
log = logging.getLogger(__name__)
log.setLevel(logging.DEBUG)

NUM_WORKERS = len(os.sched_getaffinity(0)) if hasattr(os, "sched_getaffinity") else os.cpu_count()


class DataFactory:
    def __init__(self, data_path: str):
        """
        Initializes the DataFactory with the path to the dataset.
        Currently supports RewardBench and CodeShield datasets only.
        """
        self.data_path = data_path
        self.is_rewardbench = "reward-bench" in self.data_path.lower()
        self.is_codeshield = "codeshield" in self.data_path.lower()
        self.data = self.load_hf()
        self.columns = self.data.column_names

    def maybe_subsample(self, subset: float):
        if self.is_rewardbench:
            log.warning("RewardBench datasets are not subsampled. Skipping this step.")
            return None
        if subset < 1.0:
            target_size = int(len(self.data) * subset)
            if target_size % 2:
                target_size += 1
            self.data = self.data.sort(["instance_id", "verdict"]).select(range(target_size)).flatten_indices()
            log.info(f"Subsampling dataset to {target_size} instances")

    def load_hf(self):
        data = load_dataset(self.data_path)
        if self.is_codeshield:
            data = data["test"]
        elif self.is_rewardbench:
            data = data["filtered"]
        log.info(f"Loaded dataset from {self.data_path} with {len(data)} instances")
        return data

    def filter_by_origin(self, origin: str):
        if not self.is_codeshield:
            log.warning("Dataset is not from CodeShield. Skipping origin filtering.")
            return None
        log.info(f"Filtering dataset by origin: {origin}")

        def _filter_by_origin(example, origin: str):
            return "_".join(example["instance_id"].split("_")[:-1]) == origin

        self.data = self.data.filter(_filter_by_origin, fn_kwargs={"origin": origin}, num_proc=NUM_WORKERS, desc=f"Filtering {origin} data")

    def construct_prompts(self):
        if self.is_codeshield:
            log.warning("CodeShield datasets already have prompts constructed. Skipping this step.")
            return None
        self.data = self.data.rename_columns({"prompt": "input"})

        def _construct_prompt(example, col: str):
            example["prompt"] = [
                {
                    "role": "system",
                    "content": """You are an CerebRM, a language model trained by CodeShield, specifically designed and trained to assess the overall quality of responses to human prompts. You must always think about the reasoning process before answering the question. The reasoning process and answer should be enclosed within <reason> </reason> and <solution> </solution> tags, respectively. For example:

        <reason>
        reasoning process here
        </reason>
        <solution>
        answer here
        </solution>

        The prompts can be of various types, including but not limited to open-ended questions, coding tasks, creative writing, requests for information, and more. The responses may be generated by a language model or a human and may include text, code, or both. You will receive the prompt and the generated response for each judgement session. Your evaluation should consider factors such as the helpfulness, relevance, accuracy, depth, creativity, and level of detail of the response. Your final answer must be either 'Yes' or 'No', corresponding to whether the response aligns with the judgement criteria. Any other answer will be penalized.""",
                },
                {
                    "role": "user",
                    "content": f"""Below is the question asked by the user (within [USER_QUESTION] and [/USER_QUESTION]) and the assistant's response  (within [ASSISTANT_RESPONSE] and [/ASSISTANT_RESPONSE]).
        [USER_QUESTION]
        {example["input"]}
        [/USER_QUESTION]

        [ASSISTANT_RESPONSE]
        {example[col]}
        [/ASSISTANT_RESPONSE]

        Does the response align with the judgement criteria? Answer only with 'Yes' or 'No'.""",
                },
                {"role": "assistant", "content": "<reason>\n"},
            ]
            example["verdict"] = "Yes" if col == "chosen" else "No"
            return example

        data_chosen = self.data.map(
            _construct_prompt,
            fn_kwargs={"col": "chosen"},
            num_proc=NUM_WORKERS,
            desc="Constructing prompts for 'chosen' responses",
            remove_columns=["chosen", "rejected"],
        )
        data_rejected = self.data.map(
            _construct_prompt,
            fn_kwargs={"col": "rejected"},
            num_proc=NUM_WORKERS,
            desc="Constructing prompts for 'rejected' responses",
            remove_columns=["chosen", "rejected"],
        )
        if "instance_id" not in self.columns:
            data_chosen = data_chosen.add_column("instance_id", range(len(data_chosen)))
            data_rejected = data_rejected.add_column("instance_id", range(len(data_rejected)))

        log.debug(f"Data chosen: {len(data_chosen)}\n{data_chosen.column_names}, Data rejected: {len(data_rejected)}\n{data_rejected.column_names}")

        self.data = concatenate_datasets([data_chosen, data_rejected])


def last_index(lst, value):
    return len(lst) - lst[::-1].index(value) - 1


def compute_score(yes_logprob, no_logprob):
    return np.exp(yes_logprob) / (np.exp(yes_logprob) + np.exp(no_logprob))


def compute_final_score(group_df):
    yes_row = group_df.filter(pl.col("verdict") == "Yes")
    no_row = group_df.filter(pl.col("verdict") == "No")

    score = 1 if yes_row["score"][0] > no_row["score"][0] else 0
    return pl.Series(name="final_score", values=[score, score])


@hydra.main(version_base=None, config_name="evaluate_config")
def main(cfg: Config) -> None:
    data = DataFactory(cfg.data.path)
    data.filter_by_origin(cfg.data.origin)
    data.construct_prompts()
    data.maybe_subsample(cfg.data.subset)
    test_data = data.data
    if "subset" in test_data.column_names:
        test_data = test_data.rename_columns({"subset": "category"})
    elif "aspect" in test_data.column_names:
        test_data = test_data.rename_columns({"aspect": "category"})

    llm = LLM(
        model=cfg.model.name,
        tensor_parallel_size=1,
        trust_remote_code=True,
        enable_chunked_prefill=True,
        max_num_batched_tokens=1024,
    )
    tokenizer = AutoTokenizer.from_pretrained(cfg.model.name, trust_remote_code=True)

    sampling_params_for_reasoning = SamplingParams(
        temperature=0.6,
        n=cfg.model.N,
        max_tokens=8192,
        stop="</reason>",
    )

    reasoning_responses = llm.chat(
        test_data["prompt"],
        sampling_params=sampling_params_for_reasoning,
        add_generation_prompt=False,
        continue_final_message=True,
    )
    reasoning_responses = [[x.text for x in y.outputs] for y in reasoning_responses]

    output_dir = Path(__file__).parent.parent / cfg.output.dir / cfg.data.path.split("/")[-1].lower()
    if data.is_codeshield:
        output_dir = output_dir / cfg.data.origin.lower()

    output_dir.mkdir(parents=True, exist_ok=True)
    log.info(f"Output directory: {output_dir}")
    # Save reasoning traces
    df = pl.from_arrow(test_data.data.table)
    log.info(f"Data columns: {df.columns}, {df.shape}")
    df = df.with_columns(pl.Series("reasoning", reasoning_responses, dtype=pl.List(pl.String)))

    df.write_excel(output_dir / f"reasoning_traces_{cfg.model.name.split('/')[-1]}.xlsx")
    log.info("Saved reasoning traces to Excel file.")
    # Construct responses with "Yes" answer
    yes_prompts = [
        existing_prompt[:-1]
        + [
            {
                "role": "assistant",
                "content": f"<reason>\n{x}\n</reason>\n<solution>\nYes\n</solution>",
            }
        ]
        for existing_prompt, y in zip(test_data["prompt"], reasoning_responses)
        for x in y
    ]
    # Construct responses with "No" answer
    no_prompts = [
        existing_prompt[:-1]
        + [
            {
                "role": "assistant",
                "content": f"<reason>\n{x}\n</reason>\n<solution>\nNo\n<solution>",
            }
        ]
        for existing_prompt, y in zip(test_data["prompt"], reasoning_responses)
        for x in y
    ]

    sampling_params_for_solution = SamplingParams(
        temperature=0,
        max_tokens=1,
        prompt_logprobs=1,
    )
    # Get responses for "Yes" and "No" prompts together for efficiency
    responses = llm.chat(yes_prompts + no_prompts, sampling_params_for_solution, continue_final_message=True, add_generation_prompt=False)

    # Split the responses into "Yes" and "No" responses
    yes_responses = responses[: len(yes_prompts)]
    no_responses = responses[len(yes_prompts) :]

    # Ensure that the responses are grouped by N
    yes_responses = [yes_responses[i : i + cfg.model.N] for i in range(0, len(yes_responses), cfg.model.N)]
    no_responses = [no_responses[i : i + cfg.model.N] for i in range(0, len(no_responses), cfg.model.N)]

    # Find the index of the "Yes" and "No" tokens in the responses
    yes_token_id = tokenizer.convert_tokens_to_ids("Yes")
    yes_indices = [[last_index(x.prompt_token_ids, yes_token_id) for x in y] for y in yes_responses]

    no_token_id = tokenizer.convert_tokens_to_ids("No")
    no_indices = [[last_index(x.prompt_token_ids, no_token_id) for x in y] for y in no_responses]

    # Obtain the log probabilities for the "Yes" and "No" tokens
    yes_logprobs = [[x.prompt_logprobs[yes_idx].get(yes_token_id).logprob for x, yes_idx in zip(y, yes_idx_list)] for y, yes_idx_list in zip(yes_responses, yes_indices)]

    no_logprobs = [[x.prompt_logprobs[no_idx].get(no_token_id).logprob for x, no_idx in zip(y, no_idx_list)] for y, no_idx_list in zip(no_responses, no_indices)]

    # Initialize the results DataFrame
    if (output_dir / "scores_by_model.csv").exists():
        existing_results = pl.read_csv(output_dir / "scores_by_model.csv")
    else:
        existing_results = pl.DataFrame(schema=[("model", pl.String), ("K", pl.Int64), ("score", pl.Float64)])

    # Perform self-consistency at K for K = 1,2,4,8,...N
    for i in range(int(np.log2(cfg.model.N)) + 1):
        K = 2**i
        log.info(f"Evaluating with Self Consistency K={K}")
        # Compute the scores for each instance. The score is the P("Yes")/(P("Yes") + P("No"))
        scores_per_n = [[compute_score(yes_lp, no_lp) for yes_lp, no_lp in zip(yes_lp_n[:K], no_lp_n[:K])] for yes_lp_n, no_lp_n in zip(yes_logprobs, no_logprobs)]
        # Average the scores across the cfg.model.N responses for each prompt
        scores_per_prompt = [np.mean(scores) for scores in scores_per_n]

        test_data_K = test_data.add_column("score", scores_per_prompt)
        df = pl.from_arrow(test_data_K.data.table)
        df = df.with_columns(
            (pl.col("score").filter(pl.col("verdict") == "Yes").first().over("instance_id") > pl.col("score").filter(pl.col("verdict") == "No").first().over("instance_id")).cast(pl.Int64).alias("final_score"),
        )
        df = df.select(["instance_id", "score", "verdict", "final_score", "category"])
        # Write prompt-wise results to CSV
        df.write_csv(output_dir / f"{cfg.model.name.split('/')[-1]}_K{K}.csv")

        # Create new row ensuring types match the schema
        new_row = pl.DataFrame(
            {
                "model": pl.Series([cfg.model.name], dtype=pl.String),
                "K": pl.Series([K], dtype=pl.Int64),
                "score": pl.Series([df["final_score"].mean()], dtype=pl.Float64),
            }
        )
        existing_results = pl.concat([existing_results, new_row])
        log.info(f"Average score for K={K}: {df['final_score'].mean()}")
    existing_results.write_csv(output_dir / "scores_by_model.csv")


if __name__ == "__main__":
    main()
