import os
import random
from typing import Dict, List, Optional

from datasets import Dataset, DatasetDict, concatenate_datasets, load_dataset

NUM_WORKERS = len(os.sched_getaffinity(0)) if hasattr(os, "sched_getaffinity") else os.cpu_count()


def system_prompt_map(example: Dict, aspect_map: Dict) -> Dict:
    """
    Commit-Preference Enhanced and General Preference Enhanced already have the system prompt in the "system" key. This system prompt can either be empty, or contain 2-3 principles to guide evaluation, or contain all possible principles. The goal here is to maintain the same split but to customize the principles to pointwise evaluation.
    """
    existing_system_prompt = example["system"]
    if not existing_system_prompt:
        example["num_principles"] = 0
        return example
    axis_of_evaluation = aspect_map[example["aspect"]]
    num_principles = int(existing_system_prompt.strip().split("\n\n")[-1][0])

    # Base system prompt
    base_system_prompt = """You are an CerebRM, a language model trained by CodeShield, specifically designed and trained to assess the overall quality of responses to human prompts. You must always think about the reasoning process before answering the question. The reasoning process and answer should be enclosed within <reason> </reason> and <solution> </solution> tags, respectively. For example:

<reason>
reasoning process here
</reason>
<solution>
answer here
</solution>
    
The prompts can be of various types, including but not limited to open-ended questions, coding tasks, creative writing, requests for information, and more. The responses may be generated by a language model or a human and may include text, code, or both. You will receive the prompt and the generated response for each judgement session. Your exact mandate is to evaluate the response based on a pre-specified but flexible set of criteria. Your final answer must be either 'Yes' or 'No', corresponding to whether the response aligns with the judgement criteria. Any other answer will be penalized.

The judgement criteria for this session are as follows:

1. **Helpfulness**: How well does the response address the prompt? Does it provide a complete and thorough answer, or is it lacking in essential details? This is a tenet that applies to evaluating all types of responses. Your final answer should be 'Yes' only if the response is helpful, else 'No'.

2. **Harmlessness**: Does the response contain any harmful or inappropriate content? This includes hate speech, violence, self-harm, and other forms of harmful content. This is a tenet that applies to evaluating all types of responses. Your final answer should be 'Yes' only if the response is harmless, else 'No'."""

    # Readability and Maintainability prompt
    readability_prompt = """**Readability and Maintainability**: Does the response follow best practices for readability and maintainability? Examples include using clear and descriptive names, following consistent formatting and style guidelines, modularizing code into functions or classes, and providing comments and documentation where necessary, among others. This is a tenet that applies to evaluating code responses. Your final answer should be 'Yes' only if the response is readable and maintainable, else 'No'."""

    # Runtime Efficiency prompt
    runtime_prompt = """**Runtime Efficiency**: Does the response follow best practices for runtime efficiency? Examples include using efficient algorithms and data structures, minimizing time complexity, avoiding unnecessary computations, caching results, and leveraging parallel processing or asynchronous programming techniques where appropriate, among others. This is a tenet that applies to evaluating code responses. Your final answer should be 'Yes' only if the response is runtime-efficient, else 'No'."""

    # Memory Efficiency prompt
    memory_prompt = """**Memory Efficiency**: Does the response follow best practices for memory efficiency? Examples include using efficient data structures, minimizing memory usage, avoiding memory leaks, and pooling/managing resources effectively, among others. This is a tenet that applies to evaluating code responses. Your final answer should be 'Yes' only if the response is memory-efficient, else 'No'."""

    # Security Hardness prompt
    security_prompt = """**Security Hardness**: Does the response follow best practices for security hardness? Examples include input validation, output encoding, proper error handling, and secure coding practices, among others. This is a tenet that applies to evaluating code responses. Your final answer should be 'Yes' only if the response is secure, else 'No'."""

    # Functional Correctness prompt
    functional_prompt = """**Functional Correctness**: Does the response follow best practices for functional correctness? Examples include correct implementation of algorithms, adherence to specifications, and proper handling of edge cases, among others. This is a tenet that applies to evaluating code responses. Your final answer should be 'Yes' only if the response is functionally correct, else 'No'."""

    # Construct the system prompt based on the cumulative probability
    if num_principles in [2, 3]:
        if axis_of_evaluation == "Readability and Maintainability":
            example["system"] = f"{base_system_prompt}\n\n3. {readability_prompt}\n\n"
        elif axis_of_evaluation == "Runtime Efficiency":
            example["system"] = f"{base_system_prompt}\n\n3. {runtime_prompt}\n\n"
        elif axis_of_evaluation == "Memory Efficiency":
            example["system"] = f"{base_system_prompt}\n\n3. {memory_prompt}\n\n"
        elif axis_of_evaluation == "Security Hardness":
            example["system"] = f"{base_system_prompt}\n\n3. {security_prompt}\n\n"
        elif axis_of_evaluation == "Functional Correctness":
            example["system"] = f"{base_system_prompt}\n\n3. {functional_prompt}\n\n"
        elif axis_of_evaluation in ["Helpfulness", "Harmlessness"]:
            # For Helpfulness and Harmlessness, we don't add any specific criteria
            example["system"] = f"{base_system_prompt}\n\n"
        else:
            raise ValueError(f"Unknown axis of evaluation: {axis_of_evaluation}")
    elif num_principles == 7:
        # Construct the optional criteria prompt in a random order with numbering
        criteria_prompts = [readability_prompt, runtime_prompt, memory_prompt, security_prompt, functional_prompt]
        random.shuffle(criteria_prompts)
        criteria_prompts = [f"{i + 3}. {prompt}" for i, prompt in enumerate(criteria_prompts)]
        optional_criteria_prompts = "\n\n".join(criteria_prompts)
        example["system"] = f"{base_system_prompt}\n\n{optional_criteria_prompts}\n\n"
    else:
        raise ValueError(f"Unknown number of principles: {num_principles}")

    example["system"] = example["system"].strip()
    example["num_principles"] = num_principles
    return example


def construct_prompts(example: Dict, col: str) -> List[Dict]:
    prompt = []
    example["verdict"] = "Yes" if col == "chosen" else "No"
    if example["system"]:
        prompt.append({"role": "system", "content": example["system"]})
    user_prompt = {
        "role": "user",
        "content": f"""Below is the question asked by the user (within [USER_QUESTION] and [/USER_QUESTION]) and the assistant's response  (within [ASSISTANT_RESPONSE] and [/ASSISTANT_RESPONSE]).
[USER_QUESTION]
{example["input"]}
[/USER_QUESTION]

[ASSISTANT_RESPONSE]
{example[col]}
[/ASSISTANT_RESPONSE]
        
Does the response align with the judgement criteria? Answer only with 'Yes' or 'No'.""",
    }
    generation_prompt = {"role": "assistant", "content": "<reason>\n"}
    prompt.append(user_prompt)
    prompt.append(generation_prompt)
    example["prompt"] = prompt
    return example


def process_data(data: Dataset, col: Optional[str] = None) -> Dataset:
    data = data.map(
        construct_prompts,
        fn_kwargs={"col": col},
        remove_columns=["chosen", "rejected", "input"],
        num_proc=NUM_WORKERS,
    )

    return data


def main():
    gp = load_dataset("CodeShield/General-Preference")
    cpe_md = load_dataset("CodeShield/CPE_Markdownized_Final")
    cpe = load_dataset("CodeShield/Commit-Preference-Enhanced")
    # for feature in cpe_md["train"].column_names:
    #     cpe_md = cpe_md.cast_column(feature, cpe["train"].features[feature])
    # cpe_md.push_to_hub("CodeShield/CPE_Markdownized_Final", private=True, max_shard_size="5GB")
    gp["train"] = gp["train"].add_column("instance_id", [f"gp_{i}" for i in range(len(gp["train"]))])
    gp["test"] = gp["test"].add_column("instance_id", [f"gp_{i}" for i in range(len(gp["test"]))])
    cpe["train"] = cpe["train"].add_column("instance_id", [f"cpe_{i}" for i in range(len(cpe["train"]))])
    cpe["test"] = cpe["test"].add_column("instance_id", [f"cpe_{i}" for i in range(len(cpe["test"]))])
    cpe_md["train"] = cpe_md["train"].add_column("instance_id", [f"cpe_md_{i}" for i in range(len(cpe_md["train"]))])
    cpe_md["test"] = cpe_md["test"].add_column("instance_id", [f"cpe_md_{i}" for i in range(len(cpe_md["test"]))])

    data_train = concatenate_datasets([gp["train"], cpe["train"], cpe_md["train"]])
    data_test = concatenate_datasets([gp["test"], cpe["test"], cpe_md["test"]])

    aspect_map = {i: name for i, name in enumerate(data_train.features["aspect"].names)}

    data_train = data_train.map(system_prompt_map, fn_kwargs={"aspect_map": aspect_map}, num_proc=NUM_WORKERS)
    data_test = data_test.map(system_prompt_map, fn_kwargs={"aspect_map": aspect_map}, num_proc=NUM_WORKERS)
    data_train = concatenate_datasets(
        [
            process_data(data_train, "chosen"),
            process_data(data_train, "rejected"),
        ]
    ).shuffle(seed=42)
    data_test = concatenate_datasets(
        [
            process_data(data_test, "chosen"),
            process_data(data_test, "rejected"),
        ]
    ).shuffle(seed=42)

    final_data = DatasetDict(
        {
            "train": data_train,
            "test": data_test,
        }
    )
    breakpoint()
    final_data.push_to_hub(
        repo_id="CodeShield/RLData_RM",
        private=True,
        max_shard_size="5GB",
    )


if __name__ == "__main__":
    main()
